replicaCount: 1

image:
  repository: nasgul
  tag: "v1.0.3-9e18907"
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true

autoscaling:
  enabled: false